---
title: "Extras"
output:
  html_document:
    toc: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Table of Contents

If you want to see table of contents for your Rmd files, you specify toc properties in your `_site.yml` file.

```
output:
  html_document:
    theme: readable
    toc_depth: 3
    toc_float:
      collapsed: false
```

and specify `toc: true` in your yaml at the top of your Rmd file.  

```
output:
  html_document:
    toc: true
```

See the `about.Rmd` file for an example.

## Themes

Your `_site.yml` file has a line that specifies the theme.

```
output:
  html_document:
    theme: readable
```

The following are automatically available to you: bootstrap, cerulean, cosmo, flatly, journal, lumen, paper, readable, sandstone, simplex, spacelab, united and yeti.  Try changing the theme to one of these and rebuilding your website.

You can download other bootstrap css files and put in site_libs if you want other themes.  Do a search for 'bootstrap themes free'.

## Icons

You can easily add icons to your navigation tabs.  The `icon:` line specifies the icon.  See the FontAwesome website for icons available.  Put `fa-` in front of the name.  For example a photo icon would be specified `fa-picture-o` `r icon::fa("bullhorn")`.

```
  left:
    - text: "Set-up"
      icon: fa-picture-o
      href: setup.html
```

## Customizing

You can add your own css file to customize the html.  Add to your `_site.yml` file:

```
output:
  html_document:
    theme: cosmo
    highlight: textmate
    include:
      after_body: footer.html
    css: styles.css
```

And then add a `styles.css` file to your folder.

```
h1 {
  font-color: green
}
```
